-- Sample Listings for Testing
-- Run this in Supabase SQL Editor after running supabase-schema.sql

-- Note: You need to replace 'YOUR_OWNER_USER_ID_HERE' with actual user IDs from your auth.users table
-- To get user IDs, first register some users through the app, then run:
-- SELECT id, email FROM auth.users;

-- Sample Listing 1: Modern Studio in Paris
INSERT INTO listings (
  owner_id,
  title,
  description,
  property_type,
  address,
  city,
  postal_code,
  num_bedrooms,
  num_bathrooms,
  surface_area,
  furnished,
  rent_monthly,
  charges_amount,
  charges_included,
  deposit_amount,
  available_from,
  minimum_stay_months,
  amenities,
  smoking_allowed,
  pets_allowed,
  couples_allowed,
  parties_allowed,
  status
) VALUES (
  'YOUR_OWNER_USER_ID_HERE',
  'Cozy Studio Near Sorbonne University',
  'Charming 25m² studio apartment perfectly located near Sorbonne University. Fully furnished with modern amenities, perfect for international students. The apartment includes a kitchenette, private bathroom, and high-speed WiFi. Located in a safe neighborhood with easy access to public transport.',
  'studio',
  '15 Rue des Écoles',
  'Paris',
  '75005',
  0,
  1,
  25,
  true,
  750,
  50,
  false,
  750,
  CURRENT_DATE,
  3,
  '["wifi", "washing_machine", "desk", "heating", "kitchen"]'::jsonb,
  false,
  false,
  true,
  false,
  'active'
);

-- Sample Listing 2: Apartment in Lyon
INSERT INTO listings (
  owner_id,
  title,
  description,
  property_type,
  address,
  city,
  postal_code,
  num_bedrooms,
  num_bathrooms,
  surface_area,
  furnished,
  rent_monthly,
  charges_amount,
  charges_included,
  deposit_amount,
  available_from,
  minimum_stay_months,
  amenities,
  smoking_allowed,
  pets_allowed,
  couples_allowed,
  parties_allowed,
  status
) VALUES (
  'YOUR_OWNER_USER_ID_HERE',
  'Spacious 2-Bed Apartment in Lyon',
  'Beautiful 55m² two-bedroom apartment in the heart of Lyon. Ideal for students attending Lyon universities. Recently renovated with modern furniture, full kitchen, and balcony. Close to tram stations and shopping areas. Perfect for sharing with a roommate.',
  'apartment',
  '42 Rue de la République',
  'Lyon',
  '69002',
  2,
  1,
  55,
  true,
  900,
  80,
  false,
  1800,
  CURRENT_DATE + INTERVAL '30 days',
  6,
  '["wifi", "washing_machine", "desk", "heating", "kitchen", "balcony", "dishwasher"]'::jsonb,
  false,
  false,
  true,
  false,
  'active'
);

-- Sample Listing 3: Shared Room in Toulouse
INSERT INTO listings (
  owner_id,
  title,
  description,
  property_type,
  address,
  city,
  postal_code,
  num_bedrooms,
  num_bathrooms,
  surface_area,
  furnished,
  rent_monthly,
  charges_amount,
  charges_included,
  deposit_amount,
  available_from,
  minimum_stay_months,
  amenities,
  smoking_allowed,
  pets_allowed,
  couples_allowed,
  parties_allowed,
  status
) VALUES (
  'YOUR_OWNER_USER_ID_HERE',
  'Student Room in Shared Apartment - Toulouse',
  'Affordable room in a friendly shared apartment. Part of a 3-bedroom flat with shared kitchen and living room. Great community of international students. All utilities included in rent. Walking distance to University of Toulouse.',
  'shared',
  '28 Allée Jules Guesde',
  'Toulouse',
  '31000',
  1,
  2,
  15,
  true,
  450,
  0,
  true,
  450,
  CURRENT_DATE + INTERVAL '14 days',
  1,
  '["wifi", "washing_machine", "desk", "heating", "kitchen_shared", "living_room_shared"]'::jsonb,
  false,
  false,
  false,
  false,
  'active'
);

-- Sample Listing 4: Nice Apartment near Nice
INSERT INTO listings (
  owner_id,
  title,
  description,
  property_type,
  address,
  city,
  postal_code,
  num_bedrooms,
  num_bathrooms,
  surface_area,
  furnished,
  rent_monthly,
  charges_amount,
  charges_included,
  deposit_amount,
  available_from,
  minimum_stay_months,
  amenities,
  smoking_allowed,
  pets_allowed,
  couples_allowed,
  parties_allowed,
  status
) VALUES (
  'YOUR_OWNER_USER_ID_HERE',
  'Sunny Apartment with Sea View - Nice',
  'Gorgeous 45m² apartment with partial sea view. Located in Nice, close to the university and beach. Fully equipped kitchen, modern bathroom, and plenty of natural light. Perfect for students who want to enjoy the Mediterranean lifestyle while studying.',
  'apartment',
  '18 Avenue Jean Médecin',
  'Nice',
  '06000',
  1,
  1,
  45,
  true,
  850,
  70,
  false,
  850,
  CURRENT_DATE + INTERVAL '60 days',
  6,
  '["wifi", "washing_machine", "desk", "heating", "kitchen", "air_conditioning", "balcony"]'::jsonb,
  true,
  true,
  true,
  false,
  'active'
);

-- Note: After inserting listings, you'll need to add images separately
-- For now, listings will show without images
-- To add images, run:
-- INSERT INTO listing_images (listing_id, image_url, sort_order, is_primary)
-- VALUES ('listing-id-here', 'image-url-here', 0, true);
