import type {
  Listing,
  User,
  StudentProfile,
  OwnerProfile,
  BookingRequest,
  Conversation,
  Message,
  Favorite,
  Review,
  AdminStats,
  Report,
} from './types'

// Mock Users
export const mockStudent: StudentProfile = {
  id: 'student-1',
  email: 'maria.santos@student.edu',
  firstName: 'Maria',
  lastName: 'Santos',
  avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&h=150&fit=crop',
  role: 'student',
  verificationStatus: 'verified',
  preferredLanguage: 'en',
  university: 'Sorbonne University',
  studyProgram: 'Master in Computer Science',
  studyStartDate: '2024-09-01',
  studyEndDate: '2026-06-30',
  budgetMin: 500,
  budgetMax: 900,
  preferredCities: ['Paris', 'Lyon'],
  createdAt: '2024-01-15T10:00:00Z',
}

export const mockOwner: OwnerProfile = {
  id: 'owner-1',
  email: 'jean.dupont@gmail.com',
  firstName: 'Jean-Pierre',
  lastName: 'Dupont',
  avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop',
  role: 'owner',
  verificationStatus: 'verified',
  preferredLanguage: 'fr',
  companyName: 'Dupont Immobilier',
  totalListings: 8,
  avgRating: 4.8,
  responseRate: 95,
  responseTimeHours: 2,
  createdAt: '2023-06-10T08:00:00Z',
}

export const mockAdmin: User = {
  id: 'admin-1',
  email: 'admin@semsari.ma',
  firstName: 'Admin',
  lastName: 'User',
  role: 'admin',
  verificationStatus: 'verified',
  preferredLanguage: 'en',
  createdAt: '2023-01-01T00:00:00Z',
}

// Mock Listings
export const mockListings: Listing[] = [
  {
    id: 'listing-1',
    ownerId: 'owner-1',
    ownerName: 'Jean-Pierre Dupont',
    ownerAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop',
    title: 'Charming Studio near Sorbonne University',
    description: 'Beautiful and bright studio apartment located in the heart of the Latin Quarter, just 5 minutes walk from Sorbonne University. The apartment features a fully equipped kitchen, a comfortable sleeping area, and a modern bathroom. Perfect for students looking for a quiet place to study while being close to all amenities.',
    propertyType: 'studio',
    status: 'active',
    address: '15 Rue des Ecoles',
    city: 'Paris',
    postalCode: '75005',
    latitude: 48.8499,
    longitude: 2.3469,
    hideExactAddress: true,
    surfaceArea: 25,
    numBedrooms: 1,
    numBathrooms: 1,
    floorNumber: 3,
    totalFloors: 6,
    furnished: true,
    rentMonthly: 850,
    chargesIncluded: true,
    depositAmount: 850,
    availableFrom: '2024-09-01',
    minimumStayMonths: 6,
    maximumStayMonths: 24,
    amenities: ['wifi', 'washing_machine', 'heating', 'double_glazing', 'elevator', 'intercom'],
    rules: { smoking: false, pets: false, couples: true, parties: false },
    nearbyTransport: [
      { type: 'metro', name: 'Maubert-Mutualité', distance: 200 },
      { type: 'bus', name: 'Line 63', distance: 100 },
    ],
    nearbyUniversities: [
      { name: 'Sorbonne University', distance: 300 },
      { name: 'Pierre and Marie Curie University', distance: 500 },
    ],
    images: [
      { id: 'img-1', url: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&h=600&fit=crop', isPrimary: true, sortOrder: 0 },
      { id: 'img-2', url: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&h=600&fit=crop', isPrimary: false, sortOrder: 1 },
      { id: 'img-3', url: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&h=600&fit=crop', isPrimary: false, sortOrder: 2 },
    ],
    viewCount: 234,
    favoriteCount: 45,
    verified: true,
    verifiedAt: '2024-01-20T10:00:00Z',
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-01-20T10:00:00Z',
    publishedAt: '2024-01-20T10:00:00Z',
  },
  {
    id: 'listing-2',
    ownerId: 'owner-2',
    ownerName: 'Marie Laurent',
    ownerAvatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop',
    title: 'Modern 2BR Apartment with Balcony - Lyon',
    description: 'Spacious and modern two-bedroom apartment located in the vibrant Part-Dieu district. Features a large living room with balcony, fully equipped kitchen, and two comfortable bedrooms. Ideal for students who prefer more space or want to share with a roommate.',
    propertyType: 'apartment',
    status: 'active',
    address: '45 Rue Garibaldi',
    city: 'Lyon',
    postalCode: '69003',
    latitude: 45.7602,
    longitude: 4.8574,
    hideExactAddress: true,
    surfaceArea: 55,
    numBedrooms: 2,
    numBathrooms: 1,
    floorNumber: 5,
    totalFloors: 8,
    furnished: true,
    rentMonthly: 1100,
    chargesIncluded: false,
    chargesAmount: 80,
    depositAmount: 1100,
    availableFrom: '2024-08-15',
    minimumStayMonths: 12,
    amenities: ['wifi', 'washing_machine', 'dishwasher', 'heating', 'balcony', 'elevator', 'parking'],
    rules: { smoking: false, pets: true, couples: true, parties: false },
    nearbyTransport: [
      { type: 'metro', name: 'Part-Dieu', distance: 300 },
      { type: 'tram', name: 'T1', distance: 150 },
    ],
    nearbyUniversities: [
      { name: 'University of Lyon', distance: 1500 },
      { name: 'INSA Lyon', distance: 3000 },
    ],
    images: [
      { id: 'img-4', url: 'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800&h=600&fit=crop', isPrimary: true, sortOrder: 0 },
      { id: 'img-5', url: 'https://images.unsplash.com/photo-1502672023488-70e25813eb80?w=800&h=600&fit=crop', isPrimary: false, sortOrder: 1 },
    ],
    viewCount: 189,
    favoriteCount: 32,
    verified: true,
    verifiedAt: '2024-01-18T14:00:00Z',
    createdAt: '2024-01-10T09:00:00Z',
    updatedAt: '2024-01-18T14:00:00Z',
    publishedAt: '2024-01-18T14:00:00Z',
  },
  {
    id: 'listing-3',
    ownerId: 'owner-3',
    ownerName: 'Sophie Martin',
    ownerAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&h=150&fit=crop',
    title: 'Cozy Room in Shared Apartment - Nice',
    description: 'Private room in a friendly shared apartment located near the beach and university campus. The apartment is shared with two other international students. Common areas include a spacious living room and fully equipped kitchen.',
    propertyType: 'room',
    status: 'active',
    address: '12 Avenue Jean Médecin',
    city: 'Nice',
    postalCode: '06000',
    latitude: 43.7009,
    longitude: 7.2683,
    hideExactAddress: true,
    surfaceArea: 14,
    numBedrooms: 1,
    numBathrooms: 1,
    floorNumber: 2,
    totalFloors: 4,
    furnished: true,
    rentMonthly: 550,
    chargesIncluded: true,
    depositAmount: 550,
    availableFrom: '2024-07-01',
    minimumStayMonths: 3,
    maximumStayMonths: 12,
    amenities: ['wifi', 'washing_machine', 'heating', 'shared_kitchen', 'shared_bathroom'],
    rules: { smoking: false, pets: false, couples: false, parties: false },
    nearbyTransport: [
      { type: 'tram', name: 'T1 Jean Médecin', distance: 50 },
      { type: 'bus', name: 'Line 52', distance: 100 },
    ],
    nearbyUniversities: [
      { name: 'University of Nice Sophia Antipolis', distance: 2000 },
    ],
    images: [
      { id: 'img-6', url: 'https://images.unsplash.com/photo-1598928506311-c55ez83eb08?w=800&h=600&fit=crop', isPrimary: true, sortOrder: 0 },
      { id: 'img-7', url: 'https://images.unsplash.com/photo-1598928506311-c55ece9c2?w=800&h=600&fit=crop', isPrimary: false, sortOrder: 1 },
    ],
    viewCount: 156,
    favoriteCount: 28,
    verified: true,
    verifiedAt: '2024-01-22T11:00:00Z',
    createdAt: '2024-01-20T15:00:00Z',
    updatedAt: '2024-01-22T11:00:00Z',
    publishedAt: '2024-01-22T11:00:00Z',
  },
  {
    id: 'listing-4',
    ownerId: 'owner-1',
    ownerName: 'Jean-Pierre Dupont',
    ownerAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop',
    title: 'Bright Studio in Toulouse City Center',
    description: 'Lovely renovated studio in the historic center of Toulouse, close to Place du Capitole. Features exposed brick walls, modern amenities, and plenty of natural light. Walking distance to Paul Sabatier University.',
    propertyType: 'studio',
    status: 'active',
    address: '28 Rue du Taur',
    city: 'Toulouse',
    postalCode: '31000',
    latitude: 43.6047,
    longitude: 1.4442,
    hideExactAddress: true,
    surfaceArea: 22,
    numBedrooms: 1,
    numBathrooms: 1,
    floorNumber: 1,
    totalFloors: 3,
    furnished: true,
    rentMonthly: 620,
    chargesIncluded: true,
    depositAmount: 620,
    availableFrom: '2024-09-15',
    minimumStayMonths: 6,
    amenities: ['wifi', 'heating', 'double_glazing', 'courtyard'],
    rules: { smoking: false, pets: false, couples: true, parties: false },
    nearbyTransport: [
      { type: 'metro', name: 'Capitole', distance: 300 },
      { type: 'bus', name: 'Line L1', distance: 100 },
    ],
    nearbyUniversities: [
      { name: 'Paul Sabatier University', distance: 4000 },
      { name: 'Toulouse School of Management', distance: 800 },
    ],
    images: [
      { id: 'img-8', url: 'https://images.unsplash.com/photo-1554995207-c18c203602cb?w=800&h=600&fit=crop', isPrimary: true, sortOrder: 0 },
      { id: 'img-9', url: 'https://images.unsplash.com/photo-1536376072261-38c75010e6c9?w=800&h=600&fit=crop', isPrimary: false, sortOrder: 1 },
    ],
    viewCount: 98,
    favoriteCount: 19,
    verified: true,
    verifiedAt: '2024-01-25T09:00:00Z',
    createdAt: '2024-01-23T12:00:00Z',
    updatedAt: '2024-01-25T09:00:00Z',
    publishedAt: '2024-01-25T09:00:00Z',
  },
  {
    id: 'listing-5',
    ownerId: 'owner-4',
    ownerName: 'Philippe Bernard',
    ownerAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop',
    title: 'Student Residence Room - Marseille',
    description: 'Comfortable room in a modern student residence with all utilities included. Features include 24/7 security, common study areas, laundry facilities, and a cafeteria. Perfect for students who want a hassle-free living experience.',
    propertyType: 'residence',
    status: 'active',
    address: '5 Boulevard Michelet',
    city: 'Marseille',
    postalCode: '13008',
    latitude: 43.2627,
    longitude: 5.3966,
    hideExactAddress: false,
    surfaceArea: 18,
    numBedrooms: 1,
    numBathrooms: 1,
    floorNumber: 4,
    totalFloors: 7,
    furnished: true,
    rentMonthly: 480,
    chargesIncluded: true,
    depositAmount: 480,
    availableFrom: '2024-08-01',
    minimumStayMonths: 10,
    amenities: ['wifi', 'laundry_room', 'study_room', 'security', 'cafeteria', 'bike_storage'],
    rules: { smoking: false, pets: false, couples: false, parties: false },
    nearbyTransport: [
      { type: 'metro', name: 'Rond-Point du Prado', distance: 400 },
      { type: 'bus', name: 'Line 21', distance: 100 },
    ],
    nearbyUniversities: [
      { name: 'Aix-Marseille University', distance: 500 },
    ],
    images: [
      { id: 'img-10', url: 'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800&h=600&fit=crop', isPrimary: true, sortOrder: 0 },
    ],
    viewCount: 312,
    favoriteCount: 67,
    verified: true,
    verifiedAt: '2024-01-12T16:00:00Z',
    createdAt: '2024-01-08T10:00:00Z',
    updatedAt: '2024-01-12T16:00:00Z',
    publishedAt: '2024-01-12T16:00:00Z',
  },
  {
    id: 'listing-6',
    ownerId: 'owner-2',
    ownerName: 'Marie Laurent',
    ownerAvatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop',
    title: 'Spacious Shared Apartment - Paris 13th',
    description: 'Large room available in a beautiful shared apartment in the 13th arrondissement. Two other friendly roommates, modern common spaces, and great location near universities and Asian district restaurants.',
    propertyType: 'shared',
    status: 'active',
    address: '89 Avenue de Choisy',
    city: 'Paris',
    postalCode: '75013',
    latitude: 48.8294,
    longitude: 2.3579,
    hideExactAddress: true,
    surfaceArea: 16,
    numBedrooms: 1,
    numBathrooms: 1,
    floorNumber: 6,
    totalFloors: 8,
    furnished: true,
    rentMonthly: 680,
    chargesIncluded: true,
    depositAmount: 680,
    availableFrom: '2024-10-01',
    minimumStayMonths: 6,
    amenities: ['wifi', 'washing_machine', 'dishwasher', 'heating', 'elevator', 'shared_living_room'],
    rules: { smoking: false, pets: false, couples: false, parties: false },
    nearbyTransport: [
      { type: 'metro', name: 'Place d\'Italie', distance: 500 },
      { type: 'tram', name: 'T3a', distance: 200 },
    ],
    nearbyUniversities: [
      { name: 'Paris Diderot University', distance: 2000 },
      { name: 'INALCO', distance: 1500 },
    ],
    images: [
      { id: 'img-11', url: 'https://images.unsplash.com/photo-1560185007-cde436f6a4d0?w=800&h=600&fit=crop', isPrimary: true, sortOrder: 0 },
      { id: 'img-12', url: 'https://images.unsplash.com/photo-1560185008-b033106af5c3?w=800&h=600&fit=crop', isPrimary: false, sortOrder: 1 },
    ],
    viewCount: 145,
    favoriteCount: 31,
    verified: true,
    verifiedAt: '2024-01-28T10:00:00Z',
    createdAt: '2024-01-26T14:00:00Z',
    updatedAt: '2024-01-28T10:00:00Z',
    publishedAt: '2024-01-28T10:00:00Z',
  },
]

// Mock Booking Requests
export const mockBookingRequests: BookingRequest[] = [
  {
    id: 'booking-1',
    listingId: 'listing-1',
    listing: {
      id: 'listing-1',
      title: 'Charming Studio near Sorbonne University',
      city: 'Paris',
      rentMonthly: 850,
      images: mockListings[0].images,
    },
    studentId: 'student-1',
    student: {
      id: 'student-1',
      firstName: 'Maria',
      lastName: 'Santos',
      avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&h=150&fit=crop',
    },
    ownerId: 'owner-1',
    status: 'pending',
    moveInDate: '2024-09-01',
    moveOutDate: '2025-06-30',
    introductionMessage: 'Hello! I am a master\'s student at Sorbonne University starting this September. I am very interested in your studio as it\'s perfectly located for my studies. I am clean, quiet, and responsible. I would love to schedule a visit if possible.',
    rentAmount: 850,
    depositAmount: 850,
    createdAt: '2024-07-15T14:30:00Z',
    expiresAt: '2024-07-22T14:30:00Z',
  },
  {
    id: 'booking-2',
    listingId: 'listing-4',
    listing: {
      id: 'listing-4',
      title: 'Bright Studio in Toulouse City Center',
      city: 'Toulouse',
      rentMonthly: 620,
      images: mockListings[3].images,
    },
    studentId: 'student-2',
    student: {
      id: 'student-2',
      firstName: 'Ahmed',
      lastName: 'Hassan',
      avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&h=150&fit=crop',
    },
    ownerId: 'owner-1',
    status: 'accepted',
    moveInDate: '2024-09-15',
    introductionMessage: 'Hi, I am an engineering student starting at Paul Sabatier University. Your studio looks perfect for my needs.',
    rentAmount: 620,
    depositAmount: 620,
    ownerResponse: 'Welcome Ahmed! I would be happy to have you as a tenant. Let\'s arrange the paperwork.',
    respondedAt: '2024-07-18T10:00:00Z',
    createdAt: '2024-07-16T09:00:00Z',
    expiresAt: '2024-07-23T09:00:00Z',
  },
]

// Extended Conversation type for the chat interface
export interface ChatConversation {
  id: string
  currentUserId: string
  otherUser: {
    id: string
    firstName: string
    lastName: string
    avatarUrl: string | null
    role: 'student' | 'owner'
    verificationStatus: 'pending' | 'verified' | 'rejected'
    isOnline: boolean
  }
  listing?: {
    id: string
    title: string
    city: string
    rentMonthly: number
    images: { url: string }[]
  }
  messages: ChatMessage[]
  unreadCount: number
  lastMessageAt: Date
  isArchived: boolean
}

export interface ChatMessage {
  id: string
  conversationId: string
  senderId: string
  content: string
  type: 'text' | 'image' | 'document'
  attachmentUrl?: string
  createdAt: Date
  readAt: Date | null
}

// Mock Conversations for Chat UI
export const mockConversations: ChatConversation[] = [
  {
    id: 'conv-1',
    currentUserId: 'student-1',
    otherUser: {
      id: 'owner-1',
      firstName: 'Jean-Pierre',
      lastName: 'Dupont',
      avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop',
      role: 'owner',
      verificationStatus: 'verified',
      isOnline: true,
    },
    listing: {
      id: 'listing-1',
      title: 'Charming Studio near Sorbonne University',
      city: 'Paris',
      rentMonthly: 850,
      images: [{ url: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&h=600&fit=crop' }],
    },
    messages: [
      {
        id: 'msg-1',
        conversationId: 'conv-1',
        senderId: 'student-1',
        content: "Hi! I'm interested in your studio. Is it still available for September?",
        type: 'text',
        createdAt: new Date('2024-07-15T14:30:00Z'),
        readAt: new Date('2024-07-15T15:00:00Z'),
      },
      {
        id: 'msg-2',
        conversationId: 'conv-1',
        senderId: 'owner-1',
        content: "Yes, it's available! The studio is perfect for students. Would you like to schedule a visit?",
        type: 'text',
        createdAt: new Date('2024-07-15T15:45:00Z'),
        readAt: new Date('2024-07-15T16:00:00Z'),
      },
      {
        id: 'msg-3',
        conversationId: 'conv-1',
        senderId: 'student-1',
        content: "That would be great! I'm free this weekend.",
        type: 'text',
        createdAt: new Date('2024-07-20T11:00:00Z'),
        readAt: new Date('2024-07-20T12:00:00Z'),
      },
    ],
    unreadCount: 0,
    lastMessageAt: new Date('2024-07-20T11:00:00Z'),
    isArchived: false,
  },
  {
    id: 'conv-2',
    currentUserId: 'student-1',
    otherUser: {
      id: 'owner-2',
      firstName: 'Marie',
      lastName: 'Laurent',
      avatarUrl: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop',
      role: 'owner',
      verificationStatus: 'verified',
      isOnline: false,
    },
    listing: {
      id: 'listing-2',
      title: 'Modern 2BR Apartment with Balcony - Lyon',
      city: 'Lyon',
      rentMonthly: 1100,
      images: [{ url: 'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800&h=600&fit=crop' }],
    },
    messages: [
      {
        id: 'msg-4',
        conversationId: 'conv-2',
        senderId: 'student-1',
        content: 'Hello! Is the apartment still available for August?',
        type: 'text',
        createdAt: new Date('2024-07-19T16:45:00Z'),
        readAt: null,
      },
    ],
    unreadCount: 1,
    lastMessageAt: new Date('2024-07-19T16:45:00Z'),
    isArchived: false,
  },
  {
    id: 'conv-3',
    currentUserId: 'student-1',
    otherUser: {
      id: 'owner-3',
      firstName: 'Sophie',
      lastName: 'Martin',
      avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&h=150&fit=crop',
      role: 'owner',
      verificationStatus: 'verified',
      isOnline: true,
    },
    listing: {
      id: 'listing-3',
      title: 'Cozy Room in Shared Apartment - Nice',
      city: 'Nice',
      rentMonthly: 550,
      images: [{ url: 'https://images.unsplash.com/photo-1598928506311-c55ez83eb08?w=800&h=600&fit=crop' }],
    },
    messages: [
      {
        id: 'msg-5',
        conversationId: 'conv-3',
        senderId: 'owner-3',
        content: 'Hi! Thanks for your interest. The room is available from July 1st.',
        type: 'text',
        createdAt: new Date('2024-07-18T10:00:00Z'),
        readAt: new Date('2024-07-18T10:30:00Z'),
      },
      {
        id: 'msg-6',
        conversationId: 'conv-3',
        senderId: 'student-1',
        content: "That's perfect! Can you tell me more about the other roommates?",
        type: 'text',
        createdAt: new Date('2024-07-18T11:00:00Z'),
        readAt: new Date('2024-07-18T11:15:00Z'),
      },
      {
        id: 'msg-7',
        conversationId: 'conv-3',
        senderId: 'owner-3',
        content: "Of course! There are two other students - one from Germany studying architecture and another from Spain doing her PhD in biology. They're both very friendly!",
        type: 'text',
        createdAt: new Date('2024-07-18T14:00:00Z'),
        readAt: null,
      },
    ],
    unreadCount: 1,
    lastMessageAt: new Date('2024-07-18T14:00:00Z'),
    isArchived: false,
  },
]

// Legacy Mock Messages (keeping for backward compatibility)
export const mockMessages: ChatMessage[] = mockConversations.flatMap(c => c.messages)

// Mock Favorites
export const mockFavorites: Favorite[] = [
  {
    id: 'fav-1',
    userId: 'student-1',
    listingId: 'listing-1',
    listing: {
      id: 'listing-1',
      title: 'Charming Studio near Sorbonne University',
      city: 'Paris',
      rentMonthly: 850,
      images: mockListings[0].images,
      surfaceArea: 25,
      numBedrooms: 1,
      propertyType: 'studio',
    },
    createdAt: '2024-07-10T10:00:00Z',
  },
  {
    id: 'fav-2',
    userId: 'student-1',
    listingId: 'listing-5',
    listing: {
      id: 'listing-5',
      title: 'Student Residence Room - Marseille',
      city: 'Marseille',
      rentMonthly: 480,
      images: mockListings[4].images,
      surfaceArea: 18,
      numBedrooms: 1,
      propertyType: 'residence',
    },
    createdAt: '2024-07-12T14:00:00Z',
  },
]

// Mock Reviews
export const mockReviews: Review[] = [
  {
    id: 'review-1',
    listingId: 'listing-1',
    bookingId: 'booking-old-1',
    reviewerId: 'student-old-1',
    reviewerName: 'Anna Schmidt',
    reviewerAvatar: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=150&h=150&fit=crop',
    overallRating: 5,
    accuracyRating: 5,
    communicationRating: 5,
    locationRating: 5,
    valueRating: 4,
    content: 'Amazing studio! Jean-Pierre was very helpful throughout my stay. The location is perfect for students at Sorbonne. Would highly recommend!',
    response: 'Thank you Anna! It was a pleasure having you as a tenant.',
    responseAt: '2024-06-20T10:00:00Z',
    createdAt: '2024-06-15T14:00:00Z',
  },
  {
    id: 'review-2',
    listingId: 'listing-1',
    bookingId: 'booking-old-2',
    reviewerId: 'student-old-2',
    reviewerName: 'Carlos Rodriguez',
    reviewerAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop',
    overallRating: 4,
    accuracyRating: 4,
    communicationRating: 5,
    locationRating: 5,
    valueRating: 4,
    content: 'Great place, exactly as described. Very close to the university and metro. The owner responds quickly to any issues.',
    createdAt: '2024-05-10T09:00:00Z',
  },
]

// Mock Admin Stats
export const mockAdminStats = {
  totalUsers: 2847,
  totalListings: 1432,
  activeListings: 856,
  pendingVerifications: 23,
  pendingReports: 12,
  totalBookings: 3421,
  monthlyRevenue: 45680,
  userGrowth: 12.5,
  listingGrowth: 8.3,
  bookingsThisMonth: 189,
  pendingBookings: 34,
  revenueThisMonth: 45680,
  revenueGrowth: 15.2,
  flaggedMessages: 5,
  avgResponseTime: 4,
}

// Mock Pending Listings for Admin
export const mockPendingListings = [
  {
    id: 'pending-1',
    title: 'New Studio near University Campus',
    city: 'Paris',
    rentMonthly: 720,
    image: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=400&h=300&fit=crop',
    submittedAt: '2 hours ago',
  },
  {
    id: 'pending-2',
    title: 'Shared Room in Central Apartment',
    city: 'Lyon',
    rentMonthly: 450,
    image: 'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=400&h=300&fit=crop',
    submittedAt: '5 hours ago',
  },
  {
    id: 'pending-3',
    title: 'Modern 1BR with Balcony',
    city: 'Marseille',
    rentMonthly: 680,
    image: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=400&h=300&fit=crop',
    submittedAt: '1 day ago',
  },
]

// Mock Recent Reports for Admin
export const mockRecentReports = [
  {
    id: 'report-admin-1',
    reason: 'Misleading Photos',
    entityType: 'Listing',
    entityName: 'Studio near Latin Quarter',
    reporterName: 'Maria Santos',
    severity: 'high' as const,
    createdAt: '2 hours ago',
  },
  {
    id: 'report-admin-2',
    reason: 'Inappropriate Messages',
    entityType: 'User',
    entityName: 'user_12345',
    reporterName: 'Jean Dupont',
    severity: 'high' as const,
    createdAt: '4 hours ago',
  },
  {
    id: 'report-admin-3',
    reason: 'Suspicious Activity',
    entityType: 'User',
    entityName: 'student_98765',
    reporterName: 'Marie Laurent',
    severity: 'medium' as const,
    createdAt: '1 day ago',
  },
]

// Mock Admin Users
export const mockAdminUsers = [
  {
    id: 'user-1',
    name: 'Maria Santos',
    email: 'maria.santos@student.edu',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&h=150&fit=crop',
    role: 'student' as const,
    verificationStatus: 'verified' as const,
    joinedAt: 'Jan 15, 2024',
    lastActiveAt: '2 hours ago',
    isSuspended: false,
  },
  {
    id: 'user-2',
    name: 'Jean-Pierre Dupont',
    email: 'jean.dupont@gmail.com',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop',
    role: 'owner' as const,
    verificationStatus: 'verified' as const,
    joinedAt: 'Jun 10, 2023',
    lastActiveAt: '1 hour ago',
    isSuspended: false,
  },
  {
    id: 'user-3',
    name: 'Li Wei',
    email: 'li.wei@university.cn',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&h=150&fit=crop',
    role: 'student' as const,
    verificationStatus: 'pending' as const,
    joinedAt: 'Jul 20, 2024',
    lastActiveAt: '3 hours ago',
    isSuspended: false,
  },
  {
    id: 'user-4',
    name: 'Sophie Martin',
    email: 'sophie.martin@realestate.fr',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&h=150&fit=crop',
    role: 'owner' as const,
    verificationStatus: 'verified' as const,
    joinedAt: 'Mar 5, 2024',
    lastActiveAt: '5 hours ago',
    isSuspended: false,
  },
  {
    id: 'user-5',
    name: 'Ahmed Hassan',
    email: 'ahmed.h@student.edu',
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&h=150&fit=crop',
    role: 'student' as const,
    verificationStatus: 'pending' as const,
    joinedAt: 'Jul 18, 2024',
    lastActiveAt: '1 day ago',
    isSuspended: false,
  },
  {
    id: 'user-6',
    name: 'Spam Account',
    email: 'suspicious@temp-mail.com',
    avatarUrl: null,
    role: 'student' as const,
    verificationStatus: 'rejected' as const,
    joinedAt: 'Jul 22, 2024',
    lastActiveAt: '3 days ago',
    isSuspended: true,
  },
]

// Mock Reports
export const mockReports: Report[] = [
  {
    id: 'report-1',
    reporterId: 'student-1',
    reporterName: 'Maria Santos',
    entityType: 'listing',
    entityId: 'listing-fake-1',
    reason: 'misleading_photos',
    description: 'The photos show a different apartment than what I saw during the visit.',
    status: 'pending',
    createdAt: '2024-07-18T10:00:00Z',
  },
  {
    id: 'report-2',
    reporterId: 'owner-2',
    reporterName: 'Marie Laurent',
    entityType: 'user',
    entityId: 'student-fake-1',
    reason: 'suspicious_activity',
    description: 'This user sent multiple booking requests and never showed up for visits.',
    status: 'reviewing',
    createdAt: '2024-07-16T14:00:00Z',
  },
]

// Popular cities for search
export const popularCities = [
  { name: 'Casablanca', listingCount: 342, image: '/cities/casablanca.jpg' },
  { name: 'Rabat', listingCount: 189, image: '/cities/rabat.jpg' },
  { name: 'Marrakech', listingCount: 156, image: '/cities/marrakech.jpg' },
  { name: 'Tanger', listingCount: 134, image: '/cities/tanger.jpg' },
  { name: 'Agadir', listingCount: 98, image: '/cities/agadir.jpg' },
  { name: 'Fès', listingCount: 87, image: '/cities/fes.jpg' },
]

// Amenities list
export const amenitiesList = [
  { id: 'wifi', label: 'WiFi', icon: 'Wifi' },
  { id: 'washing_machine', label: 'Washing Machine', icon: 'WashingMachine' },
  { id: 'dishwasher', label: 'Dishwasher', icon: 'Utensils' },
  { id: 'heating', label: 'Heating', icon: 'Thermometer' },
  { id: 'air_conditioning', label: 'Air Conditioning', icon: 'Wind' },
  { id: 'elevator', label: 'Elevator', icon: 'ArrowUpDown' },
  { id: 'parking', label: 'Parking', icon: 'Car' },
  { id: 'balcony', label: 'Balcony', icon: 'Home' },
  { id: 'terrace', label: 'Terrace', icon: 'Sun' },
  { id: 'garden', label: 'Garden', icon: 'Trees' },
  { id: 'double_glazing', label: 'Double Glazing', icon: 'Square' },
  { id: 'intercom', label: 'Intercom', icon: 'Phone' },
  { id: 'security', label: 'Security', icon: 'Shield' },
  { id: 'bike_storage', label: 'Bike Storage', icon: 'Bike' },
  { id: 'laundry_room', label: 'Laundry Room', icon: 'Shirt' },
  { id: 'study_room', label: 'Study Room', icon: 'BookOpen' },
  { id: 'cafeteria', label: 'Cafeteria', icon: 'Coffee' },
]

// Moroccan universities
export const universities = [
  'Université Mohammed V - Rabat',
  'Université Hassan II - Casablanca',
  'Université Cadi Ayyad - Marrakech',
  'Université Abdelmalek Essaâdi - Tétouan/Tanger',
  'Université Ibn Zohr - Agadir',
  'Université Sidi Mohamed Ben Abdellah - Fès',
  'Al Akhawayn University - Ifrane',
  'Université Internationale de Rabat (UIR)',
  'EMI - École Mohammadia d’Ingénieurs',
  'ENCG (Écoles Nationales de Commerce et de Gestion)',
]
